# Generated by Django 5.2 on 2025-05-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название места"),
                ),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=50, verbose_name="Тип заведения")),
            ],
            options={
                "verbose_name": "Тип заведения",
                "verbose_name_plural": "Типы заведений",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "face_img",
                    models.ImageField(
                        upload_to="media/cards/faces/", verbose_name="Главное фото"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Например: г. Бишкек, ул. Ленина, 25",
                        max_length=255,
                        verbose_name="Полный адрес",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Например: Бишкек",
                        max_length=100,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название заведения"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Например: +996707123456",
                        max_length=20,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на WhatsApp"
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Telegram"
                    ),
                ),
                ("site", models.URLField(blank=True, null=True, verbose_name="Сайт")),
                ("description", models.TextField(verbose_name="Описание")),
                ("start_work", models.TimeField(verbose_name="Время открытия")),
                ("stops_work", models.TimeField(verbose_name="Время закрытия")),
                (
                    "work_days",
                    models.CharField(
                        help_text="например: Пн-Вс или Пн-Пт",
                        max_length=50,
                        verbose_name="Дни работы",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/cards/videos/",
                        verbose_name="Видео заведения",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="categories.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="cards.place",
                        verbose_name="Локация",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="cards.type",
                        verbose_name="Тип заведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка",
                "verbose_name_plural": "Карточки",
            },
        ),
        migrations.CreateModel(
            name="CardPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/cards/photos/", verbose_name="Фото"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="cards.card",
                        verbose_name="Карточка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото заведения",
                "verbose_name_plural": "Фотки заведения",
            },
        ),
        migrations.CreateModel(
            name="CardVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.FileField(
                        upload_to="media/cards/videos/", verbose_name="Видео"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="cards.card",
                        verbose_name="Карточка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео заведения",
                "verbose_name_plural": "Видео заведения",
            },
        ),
        migrations.CreateModel(
            name="FeaturedCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_entries",
                        to="cards.card",
                        verbose_name="Карточка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекламная карточка",
                "verbose_name_plural": "Рекламные карточки",
            },
        ),
    ]
