# Generated by Django 5.2 on 2025-05-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название типа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип заведения",
                "verbose_name_plural": "Типы заведений",
            },
        ),
        migrations.AddField(
            model_name="card",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cards/videos/",
                verbose_name="Видео заведения",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cards",
                to="cards.type",
                verbose_name="Тип заведения",
            ),
        ),
    ]
