# Generated by Django 5.2 on 2025-05-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Например: +996707123456",
                max_length=20,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.CreateModel(
            name="CardPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(upload_to="cards/photos/", verbose_name="Фото"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="cards.card",
                        verbose_name="Карточка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото заведения",
                "verbose_name_plural": "Фотки заведения",
            },
        ),
    ]
