# Generated by Django 5.2 on 2025-05-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Например: Бишкек",
                max_length=100,
                null=True,
                verbose_name="Город",
            ),
        ),
    ]
