# Generated by Django 5.2 on 2025-05-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_card_phone_number_cardphoto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredcard",
            name="added_at",
        ),
        migrations.RemoveField(
            model_name="featuredcard",
            name="expires_at",
        ),
    ]
