# Generated by Django 5.2 on 2025-05-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_type_card_video_card_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="type",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="cards.type",
                verbose_name="Тип заведения",
            ),
            preserve_default=False,
        ),
    ]
