# Generated by Django 5.2 on 2025-05-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_card_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="type",
            field=models.CharField(
                choices=[
                    ("food", "🍽 Еда"),
                    ("religion", "🕌 Религия"),
                    ("services", "🛠 Услуги"),
                    ("business", "💼 Работа и бизнес"),
                    ("family", "👨\u200d👩\u200d👧\u200d👦 Семья и дети"),
                ],
                max_length=20,
                verbose_name="Тип заведения",
            ),
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
