# Generated by Django 5.2 on 2025-05-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_alter_card_type_delete_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="address",
            field=models.CharField(
                default=True,
                help_text="Например: г. Бишкек, ул. Ленина, 25",
                max_length=255,
                verbose_name="Полный адрес",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card",
            name="type",
            field=models.CharField(
                choices=[
                    ("food", "Еда"),
                    ("religion", "Религия"),
                    ("services", "Услуги"),
                    ("business", "Работа и бизнес"),
                    ("family", "Семья и дети"),
                ],
                max_length=20,
                verbose_name="Тип заведения",
            ),
        ),
    ]
