# Generated by Django 5.2 on 2025-05-06 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_card_address_alter_card_type"),
        ("reviews", "0002_review_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="cards.card",
            ),
        ),
    ]
